"""Init

Revision ID: 4f5f6afca1b9
Revises: 
Create Date: 2025-01-31 06:12:32.037506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5f6afca1b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('test_whitelist',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_whitelist')
    op.drop_table('test_user')
    # ### end Alembic commands ###
